---
name: "Alicja Gosiewska"
photo: "Alicja_circle.png"
social_media:
  github: "agosiewska"
  linkedin: "alicja-gosiewska"
  scholar: "YiwwR6EAAAAJ"
about:
  - "Data enthusiast with 4+ experience in data science."
  - "Skilled in R and Python."
  - "Interested in explainable artificial intelligence (XAI) and data visualization."
  - "With a strong background in mathematics (Bachelor) and statistics (Master)."

