---
name: "Alicja Gosiewska"
photo: "Alicja_circle.png"
social_media:
  github: "agosiewska"
  outside_github_stars:
    - "ModelOriented/auditor"
    - "ModelOriented/rSAFE"
    - "ModelOriented/iBreakDown"
    - "MI2DataLab/survxai"
    - "ModelOriented/localModel"
    - "ModelOriented/shapper"
    - "BioGenies/countfitteR"
    - "ModelOriented/EloML"
  linkedin: "alicja-gosiewska"
  scholar: "YiwwR6EAAAAJ"
  twitter: "alicjagosiewska"
  cran_packages:
    - "auditor"
    - "rSAFE"
    - "shapper"
    - "iBreakDown"
    - "BLModel"
    - "survxai"
    - "localModel"
    - "countfitteR"
    
about: "./data/about.md"
panels:
  industry: "./data/industry.md"
  academia: "./data/academia.md"
  community: "./data/community.md"
  competences: "./data/competences.md"
  education: "./data/education.md"
timeline: "./data/timeline.csv"
fork_info: true
